// <auto-generated />
namespace Ejercicio02.AccountManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class ClientDocument : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ClientDocument));
        
        string IMigrationMetadata.Id
        {
            get { return "201911152124319_Client Document"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
